apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   kompose.cmd: C:\Users\Amit\kmpose\kompose.exe convert
  #   kompose.version: 1.26.0 (40646f47)
  # creationTimestamp: null
  # labels:
  #   io.kompose.service: admin-server
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-server
  strategy: {}
  template:
    # metadata:
    #   annotations:
    #     kompose.cmd: C:\Users\Amit\kmpose\kompose.exe convert
    #     kompose.version: 1.26.0 (40646f47)
    #   creationTimestamp: null
    #   labels:
    #     io.kompose.service: admin-server
    spec:
      containers:
        - command:
            - ./dockerize
            - -wait=tcp://discovery-server:8761
            - -timeout=60s
            - --
            - java
            - org.springframework.boot.loader.JarLauncher
          image: springcommunity/spring-petclinic-admin-server
          name: admin-server
          ports:
            - containerPort: 9090
          resources:
            limits:
              memory: 512M
      restartPolicy: Always
status: {}
