apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Amit\kmpose\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana-server
  name: grafana-server
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: grafana-server
status:
  loadBalancer: {}
